### ISSUE TITLE
Request for o-colors component/design spec

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/design#3]
I'm guessing we can follow the pattern of [FT's o-colors component](http://registry.origami.ft.com/components/o-colors@3.0.0).

**Comment by aarmour** [comment]
Placeholder for [o-colors](https://github.com/pearson-higher-ed/o-colors). Use that repo's issues for any discussion related to the component.

**Comment by parkerpearson** [comment]
@edzee Greg (@antelopeb) has put out a first pass at the colors in the o-colors repo. Can you take a look at the colors that are in there from a framework standpoint? We should probably get some design documentation on colors put together too at some point.

**Comment by parkerpearson** [comment]
This has been added to the design site.
