### ISSUE TITLE
Request for o-typography component/design spec

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/design#4]
The FT [o-typography component](http://registry.origami.ft.com/components/o-typography@1.16.4) could be a good guideline.

**Comment by aarmour** [comment]
There was previously a placeholder for `o-colors`, but there is none for `o-typography`. At what point should the component repository be created? (Aside: we [dropped](https://github.com/Pearson-Higher-Ed/he-origami/issues/6) the `he-` part of the prefix in the component name).

**Comment by parkerpearson** [comment]
This has been added to the design site.
