### ISSUE TITLE
Define standard viewport breakpoints

### ISSUE THREAD

**Issue by aarmour** [Pearson-Higher-Ed/design#5]
Define a standard set of responsive breakpoints and implement a component to encode the media queries (e.g., o-responsive; see Bootstrap for an [example](http://getbootstrap.com/css/#responsive-utilities) set of selectors). One example, based on @parkerpearson's latest header designs:

```
.o-responsive__viewport-phone-sm--visible           // width < 480px
.o-responsive__viewport-phone--visible              // 480px <= width < 768px
.o-responsive__viewport-tablet--visible             // 768px <= width < 1024px
.o-responsive__viewport-desktop--visible            // 1024px <= width

.o-responsive__viewport-phone-sm--hidden            // width < 480px
.o-responsive__viewport-phone--hidden               // 480px <= width < 768px
.o-responsive__viewport-tablet--hidden              // 768px <= width < 1024px
.o-responsive__viewport-desktop--hidden             // 1024px <= width

.o-responsive__viewport-*--block
.o-responsive__viewport-*--inline
.o-responsive__viewport-*--inline-block
```

**Comment by aarmour** [comment]
From CSS tricks: [Media queries for standard devices](https://css-tricks.com/snippets/css/media-queries-for-standard-devices/).

**Comment by aarmour** [comment]
Using sizes is probably more future-resistant than device types: `xs`, `sm`, `md`, `lg`.

**Comment by parkerpearson** [comment]
It would probably be good to consider larger screens as well, something like

1280px
1440px
1680px

**Comment by aarmour** [comment]
@parkerpearson Bootstrap's highest breakpoint is 1200px (`lg`, in their case). Do we have any known use cases for changing the layout for very large screens?

**Comment by aarmour** [comment]
Foundation 5 goes up to xxl at 1921px.

**Comment by parkerpearson** [comment]
I guess it would just be a decision we make. If we don't want to go larger
than 1200px-ish, then we should cap the size of our design. I know right
now Console will just keep getting larger and larger without reflowing to
take advantage of the space, which looks weird.

**Comment by aarmour** [comment]
I'm considering an `o-visibility` module. It would contain the classes for controlling visibility at the various breakpoints, with additional classes for other cases—e.g., `o-visibility--hidden`, `o-visibility--sr-hidden` (invisible to screen readers), `o-visibility--landscape-{hidden|visible}`, `o-visibility--portrait-{hidden|visible}`, `o-visibility--print-{hidden|visible}`.

**Comment by aarmour** [comment]
Created a placeholder for [o-visibility](https://github.com/Pearson-Higher-Ed/o-visibility).

**Comment by antelopeb** [comment]
Should we consider pre-empting this with a o-breakpoints or o-grid component? Or both? That would allow us to define the grid system on the page and them we could put o-visibility in place with o-breakpoints as a dependency.

**Comment by aarmour** [comment]
The breakpoints and visibility helpers could probably exist in the same component (`o-responsive`, or something similar), which would be a dependency for `o-grid`.

**Comment by parkerpearson** [comment]
Added at http://pearson-higher-ed.github.io/design/c/breakpoints/
