### ISSUE TITLE
Remove product-specific language

### ISSUE THREAD

**Issue by aarmour** [Pearson-Higher-Ed/design#6]
Like the Origami components themselves, I recommend that the visual design guidelines be product-agnostic, preferring general descriptions of common patterns to specific product examples, as it will serve a wider audience.

For example, in the [Application Header](http://pearson-higher-ed.github.io/design/docs/ui-components/application-header/), describe how consumers have the ability to insert page-oriented nav items into the Menu and show an example, but don't call the particular product out by name.

(@parkerpearson @edzee @Bluemeredith)

**Comment by parkerpearson** [comment]
I think this makes sense.
